### ISSUE TITLE
Proposed Search endpoint

### ISSUE THREAD

**Issue by MarshallOfSound** [gmusic-utils/gmusic-ui.js#2]
## New Methods

| Namespace | Method | Return Value |
| --- | --- | --- |
| `search` | `isSearching()` | `Boolean` - True if currently searching, False otherwise |
| `search` | `getSearchText()` | `String` - The current text the user is searching for |
| `search` | `search(text)` | `undefined` - Performs a GPM search for the given text |
| `search` | `getResults()` | `Object` - An object in the format explained below |
| `search` | `playResult(Artist | Album | Track)` | `undefined` - Immediately plays the specified result |
### `change:search`

Will fire whenever a new search is completed and will emit with the result of `getResults()`
## Results Object

``` js
{
  artists: Artist[],
  albums: Album[],
  tracks: Track[]
}
```

`Track` is already a defined struct in our [docs](https://github.com/gmusic-utils/gmusic-ui.js#track)  
`Artist` will be a new struct of the form

``` js
{
  id: String,
  name: String,
  image: String
}
```

`Album` will be a new struct of the form

``` js
{
  id: String,
  name: String,
  artist: String,
  albumArt: String,
}
```

I'm going to start work on this lot, feedback is welcome 👍

**Comment by twolfson** [comment]
Looks good to me. `Void` should be replaced with `undefined` since that's JS's default to return when there is no `return` call
